#services:
#  postgres:
#    image: 'postgres:latest'
#    container_name: urlshortener
#    environment:
#      - 'POSTGRES_DB=urlshortener'
#      - 'POSTGRES_PASSWORD=123'
#      - 'POSTGRES_USER=volosha'
#    ports:
#      - '5432:5432'
